# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cluster_py_C <- function(n, sigma, theta) {
    .Call('_BNPvegan_cluster_py_C', PACKAGE = 'BNPvegan', n, sigma, theta)
}

rarefy_C <- function(freq, n, K, verbose) {
    .Call('_BNPvegan_rarefy_C', PACKAGE = 'BNPvegan', freq, n, K, verbose)
}

prob_LL3_Cpp <- function(n, alpha, sigma, phi) {
    .Call('_BNPvegan_prob_LL3_Cpp', PACKAGE = 'BNPvegan', n, alpha, sigma, phi)
}

prob_Weibull_Cpp <- function(n, phi, lambda) {
    .Call('_BNPvegan_prob_Weibull_Cpp', PACKAGE = 'BNPvegan', n, phi, lambda)
}

truncationpoint_LL3_Cpp <- function(n, alpha, sigma, phi, tolerance) {
    .Call('_BNPvegan_truncationpoint_LL3_Cpp', PACKAGE = 'BNPvegan', n, alpha, sigma, phi, tolerance)
}

truncationpoint_Weibull_Cpp <- function(n, phi, lambda, tolerance) {
    .Call('_BNPvegan_truncationpoint_Weibull_Cpp', PACKAGE = 'BNPvegan', n, phi, lambda, tolerance)
}

sample_Kinf_LL3_Cpp <- function(n_samples, n, k, alpha, sigma, phi, tolerance) {
    .Call('_BNPvegan_sample_Kinf_LL3_Cpp', PACKAGE = 'BNPvegan', n_samples, n, k, alpha, sigma, phi, tolerance)
}

sample_Kinf_Weibull_Cpp <- function(n_samples, n, k, phi, lambda, tolerance) {
    .Call('_BNPvegan_sample_Kinf_Weibull_Cpp', PACKAGE = 'BNPvegan', n_samples, n, k, phi, lambda, tolerance)
}

get_n_target_saturation_LL3 <- function(n, k, alpha, sigma, phi, Kinf, target) {
    .Call('_BNPvegan_get_n_target_saturation_LL3', PACKAGE = 'BNPvegan', n, k, alpha, sigma, phi, Kinf, target)
}

get_n_target_saturation_Weibull <- function(n, k, phi, lambda, Kinf, target) {
    .Call('_BNPvegan_get_n_target_saturation_Weibull', PACKAGE = 'BNPvegan', n, k, phi, lambda, Kinf, target)
}

