# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EPPF_Dirichlet <- function(counts, alpha) {
    .Call('_BNPvegan_EPPF_Dirichlet', PACKAGE = 'BNPvegan', counts, alpha)
}

EPPF_PitmanYor <- function(counts, alpha, sigma) {
    .Call('_BNPvegan_EPPF_PitmanYor', PACKAGE = 'BNPvegan', counts, alpha, sigma)
}

