# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cluster_py_C <- function(n, sigma, theta) {
    .Call('_BNPvegan_cluster_py_C', PACKAGE = 'BNPvegan', n, sigma, theta)
}

rarefy_C <- function(freq, n, K) {
    .Call('_BNPvegan_rarefy_C', PACKAGE = 'BNPvegan', freq, n, K)
}

